name: noteflowaiapp
description: "AI-Powered Notes App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase & Google
  google_mlkit_text_recognition: ^0.14.0
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0

  # Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  # supabase
  supabase_flutter: ^2.8.0

  # utils
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  flutter_animator: ^3.2.2
  flutter_dotenv: ^5.2.1
  toastification: ^2.3.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  timeago: ^3.7.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  rive: ^0.13.15
  http: ^1.2.2
  uuid: ^4.5.1
  path:

  # Images
  cached_network_image: ^3.4.1
  easy_image_viewer: ^1.5.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/noteflowai_ios.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/images/

  fonts:
    - family: Madani
      fonts:
        - asset: assets/fonts/madani_regular.ttf
          weight: 400
        - asset: assets/fonts/madani_light.ttf
          weight: 300
        - asset: assets/fonts/madani_medium.ttf
          weight: 500
        - asset: assets/fonts/madani_bold.ttf
          weight: 700
